BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('board.urls')),
]

BulletinBoard/board/urls.py
from .views import AdvertisementView, AdvertisementDetailView, AdvCreate, AdvUpdate, AdvDeleteView, respCreate, UserDetailView, confirm_resp, delete_resp
from django.urls import path

urlpatterns = [
    path('', AdvertisementView.as_view(), name='index'),
    path('adv/<int:pk>/', (AdvertisementDetailView.as_view()), name='adv_detail'),
    path('create/', AdvCreate.as_view(), name='create'),
    path('resp/create/<int:pk>', respCreate, name='createresp'),
    path('<int:pk>/delete/', AdvDeleteView.as_view(), name='adv_delete'),
    path('update/<int:pk>/', AdvUpdate.as_view(), name='adv_update'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='userinfo'),
    path('resp/confirm/<int:id>/', confirm_resp, name='confirm_resp'),
    path('resp/delete/<int:id>/', delete_resp, name='delete_resp'),

]

BulletinBoard/board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

class Advertisement(models.Model):
    CATEGORY_CHOICES = [
        ('TK', 'Tanks'),
        ('HE', 'Heals'),
        ('DD', 'DD'),
        ('MH', 'Merchants'),
        ('GM', 'Guild Masters'),
        ('QG', 'Quest Givers'),
        ('BS', 'Blacksmiths'),
        ('TN', 'Tanners'),
        ('PM', 'Potion Makers'),
        ('SM', 'Spell Masters'),
    ]

    heading = models.CharField(max_length=64, verbose_name="Заголовок")
    text = RichTextUploadingField(verbose_name="Текст объявления")
    publication_date = models.DateTimeField(auto_now_add=True)
    changepublication_date = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=2,
                                choices=CATEGORY_CHOICES,
                                verbose_name="Категория")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Author')
    rating = models.IntegerField(default=0, verbose_name="рейтинг")

    # responses = models.ForeignKey('Response', on_delete=models.CASCADE, related_name='Отклики')

    class Meta():
        ordering = ['-publication_date', '-changepublication_date']
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return f'Объявление {self.heading}, категория {self.category} от {self.author.username}'

    def get_absolute_url(self):
        return f'/adv/{self.id}'

class Response(models.Model):
    tekst = models.TextField(verbose_name='Текст отклика')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='responseUser', verbose_name='Пользователь')
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE, related_name='advertisement', verbose_name='Объявление')
    publication_date = models.DateTimeField(auto_now_add=True)
    changepublication_date = models.DateTimeField(auto_now=True)
    is_confirm = models.BooleanField(default=False)

    class Meta():
        ordering = ['publication_date', '-changepublication_date']
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return f'Отклик от {self.user.username} к объявлению {self.advertisement.heading}: {self.tekst}'

    def get_absolute_url(self):
        return f'/adv/resp/{self.id}'





# Create your models here.

BulletinBoard/board/forms.py
from django.forms import ModelForm, BooleanField
from .models import Advertisement, Response


class AdvCreateForm(ModelForm):
    # check_box = BooleanField(label='Подтвердить создание')


    class Meta:
        model = Advertisement
        fields = ['heading', 'text', 'category', 'category']

class RespCreateForm(ModelForm):
    # check_box = BooleanField(label='Подтвердить создание')


    class Meta:
        model = Response
        fields = ['tekst',]

BulletinBoard/board/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
import os
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, request
from .models import Advertisement, Response, User
from django.views.generic.base import View
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import AdvCreateForm, RespCreateForm
from .filters import AdvertisementFilter
from django.contrib.auth.decorators import login_required


class AdvertisementView(View):
    def get(self, request):
        adv = Advertisement.objects.all()

        return render(request, 'board/advertisement.html', {'adv_list': adv})


class AdvertisementDetailView(DetailView):
    model = Advertisement
    template_name = 'board/adv_detail.html'
    context_object_name = 'adv'


class AdvCreate(LoginRequiredMixin, CreateView):
    template_name = 'board/adv_create.html'
    form_class = RespCreateForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.user = self.request.user
        fields.save()

        return super().form_valid(form)


# class RespCreate(LoginRequiredMixin, CreateView):
#     template_name = 'board/adv_create.html'
#     form_class = AdvCreateForm
#     success_url = reverse_lazy('index')
#
#     def form_valid(self, form):
#         fields = form.save(commit=False)
#         fields.author = self.request.user
#         fields.save()
#
#         return super().form_valid(form)


def respCreate(request, pk):

    if request.method == 'POST':
        form = RespCreateForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['tekst']
            advertisement = Advertisement.objects.get(pk=pk)
            Response.objects.create(tekst=text, advertisement=advertisement, user=request.user)

        return redirect('adv_detail', pk)
    else:
        form = RespCreateForm()
    return render(request, 'board/createresp.html', {'form': form})



class AdvSearch(View):
    pass

class AdvUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'board/adv_update.html'
    form_class = AdvCreateForm
    model = Advertisement
    context_object_name = 'adv'
    # success_url = reverse_lazy('adv_detail')
    permission_required = ('Advertisement.change_post')


    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Advertisement.objects.get(pk=id)



class AdvDeleteView(LoginRequiredMixin, DeleteView):
    model = Advertisement
    template_name = 'board/adv_delete.html'
    queryset = Advertisement.objects.all()
    success_url = ''
    context_object_name = 'adv'



# class UserDetailView(DetailView):
#     model = User
#     template_name = 'board/user_detail.html'
#     context_object_name = 'user'


class UserDetailView(ListView):
    model = Advertisement
    template_name = 'board/user_detail.html'
    context_object_name = 'adv'
    def get_filter(self):
        return AdvertisementFilter(self.request.GET, queryset=super().get_queryset())

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *args, **kwargs):
        return {
            **super().get_context_data(*args, **kwargs),
            'filter': self.get_filter(),
        }


    def get_filter(self):
        return AdvertisementFilter(self.request.GET, queryset=super().get_queryset())

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *args, **kwargs):
        return {
            **super().get_context_data(*args, **kwargs),
            'filter': self.get_filter(),
        }


@login_required()
def confirm_resp(request, id):
     resp = Response.objects.get(id=id)
     resp.is_confirm = True
     resp.save()
     author = resp.user
     adv = resp.advertisement.heading
     id = request.user.id

     send_mail(
         'Подтвержден ваш отклик на объявление',
         f'Подтвержден ваш отклик на объявление {adv}',
         f"{os.getenv('MY_MAIL')}",
         [f'{author.email}'],
         fail_silently=False,
     )
     return redirect(f'/user/{id}')

@login_required()
def delete_resp(request, id):
     resp = Response.objects.get(id=id)
     resp.delete()

     id = request.user.id


     return redirect(f'/user/{id}')

BulletinBoard/templates/board/adv_create.html
{% extends 'board/default.html' %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>


{% block title %}
Создание объявления
{% endblock title %}

{% block front %}
Создание объявления
{% endblock front %}

{% block content %}


<h3>Новое объявление</h3>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Новое объявление">
</form>


{% endblock content %}

BulletinBoard/templates/board/adv_delete.html
{% extends 'board/default.html' %}


{% block title %} {{ adv.title }} {% endblock title %}
{% block front %} {{ adv.title }} {% endblock front %}

{% block front %}
Удаление Новости
{% endblock front %}
{% block content %}

<div class="container mt-3">
  <div class="card mb-3">
    <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">

        {% if user.is_authenticated %}
        <a class="nav-link " href="{% url 'adv_update' adv.pk%}">Редактировать</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'adv_delete' adv.pk %}">Удалить</a>

        {% endif %}
    </ul>
  </div>
    <div class="card-body">
      <h5 class="card-title">{{ adv.heading }}</h5>
      <p class="card-text">{{adv.text | safe }}</p>

    </div>
    <div class="card-footer text-muted">
      {{ adv.publication_date|date:'d.m.Y H:i' }}   Рейтинг: {{  adv.rating }}
      {% if user.is_authenticated %}

      {% endif  %}


    </div>
  </div>
  <div class="card mb-1">
    {% get_my_responses_list adv=adv as resp%}
    {% if resp|length %}
    {% for res in resp %}
      <h4 class="card-header">{{ res.user.username }}</h4>
    <div class="card-body">

      <p class="card-text">{{ res.tekst }}</p>

    </div>
    <div class="card-footer text-muted">
      {{ res.publication_date|date:'d.m.Y H:i' }}


    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Подтвердить">
</form>


{% endblock content %}

BulletinBoard/templates/board/adv_detail.html
{% extends 'board/default.html' %}
{% load board_tags %}

{% block title %} {{ adv.title }} {% endblock title %}
{% block front %} {{ adv.title }} {% endblock front %}
{% block content %}

<div class="container mt-3">
  <div class="card mb-3">
    <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">

        {% if user.is_authenticated %}
        <a class="nav-link " href="{% url 'adv_update' adv.id%}">Редактировать</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'adv_delete' adv.id%}">Удалить</a>

        {% endif %}
    </ul>
  </div>
    <div class="card-body">
      <h5 class="card-title">{{ adv.heading }}</h5>
      <p class="card-text">{{adv.text | safe }}</p>

    </div>
    <div class="card-footer text-muted">
      {{ adv.publication_date|date:'d.m.Y H:i' }}   Рейтинг: {{  adv.rating }}
      {% if user.is_authenticated %}
      <a href="{% url 'createresp' adv.id %}"> Добавить отклик</a>
      {% endif  %}


    </div>
  </div>
  <div class="card mb-1">
    {% get_my_responses_list adv=adv as resp%}
    {% if resp|length %}
    {% for res in resp %}
      <h4 class="card-header">{{ res.user.username }}</h4>
    <div class="card-body">

      <p class="card-text">{{ res.tekst }}</p>

    </div>
    <div class="card-footer text-muted">
      {{ res.publication_date|date:'d.m.Y H:i' }}


    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>



{% endblock content %}

BulletinBoard/templates/board/adv_update.html
{% extends 'board/default.html' %}


{% block title %} {{ adv.title }} {% endblock title %}


{% block front %}
Удаление Объявления
{% endblock front %}
{% block content %}


<h3>{{adv.heading}}</h3>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value='Редактирование Объявления'>
</form>


{% endblock content %}

BulletinBoard/templates/board/advertisement.html
{% extends 'board/default.html' %}
{% load board_tags %}

{% block title %} Объявления {% endblock title %}
{% block front %} Все Объявления {% endblock front %}
{% block content %}
{% for adv in adv_list %}
<div class="container mt-3">
  <div class="card mb-3">
    <h5 class="card-header">{{ adv.get_category_display }}</h5>
    <div class="card-body">
      <h5 class="card-title">{{ adv.heading }}</h5>
      <p class="card-text">{{adv.text | safe |truncatewords:30}}</p>
      <a href="{% url 'adv_detail' adv.pk %}" class="btn btn-primary">Читать полностью</a>
    </div>
    <div class="card-footer text-muted">
      {{ adv.publication_date|date:'d.m.Y H:i' }}   Рейтинг: {{  adv.rating }}
      Откликов:
      {% get_my_responses adv=adv %}

    </div>
  </div>
</div>


{% endfor %}
{% endblock content %}

BulletinBoard/templates/board/createresp.html
{% extends 'board/default.html' %}
{% load board_tags %}

{% block title %} Добавление Отклика {% endblock title %}
{% block front %} Добавление Отклика {% endblock front %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='Добавить'>
</form>



{% endblock content %}

BulletinBoard/templates/board/default.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
           {% endblock title %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" >{% block front %}{% endblock front %}</a>
        <a class="navbar-brand" href="{% url 'userinfo' user.pk %}">{{ user.username }}</a>
        {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'account_logout' %}">Выйти</a>
        {%else%}
          <a class="navbar-brand" href="{% url 'account_login' %}">Войти</a>
          <a class="navbar-brand" href="{% url 'account_singin' %}">Зарегистрироваться</a>

        {% endif  %}

        <div class="navbar-expand" id="navbarSupportedContent">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            <a class="nav-link" href="{% url 'create' %}">Создать объявление</a>
            <a class="nav-link" href="#">Pricing</a>
            <a class="nav-link disabled">Disabled</a>
          </div>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

BulletinBoard/templates/board/user_detail.html
{% extends 'board/default.html' %}
{% load board_tags %}

{% block title %} {{ user.username }} {% endblock title %}
{% block front %} <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
         </form> {% endblock front %}
{% block content %}

{% get_userpost_list user=user as posts %}

{% if posts %}
{% for post in filter.qs %}
По объявлению {{ post.heading }} {%get_my_responses adv=post%} откликов
<div class="card mb-1">
    {% get_my_responses_list adv=post as resp%}
    {% if resp|length %}
    {% for res in resp %}

      <h4 class="card-header">{{ res.user.username }}</h4>
    <div class="card-body">

      <p class="card-text">{{ res.tekst }}</p>

    </div>
    <div class="card-footer text-muted">
      {{ res.publication_date|date:'d.m.Y H:i' }}
        {% if not res.is_confirm %}
        <button onclick="window.location.href = '{% url 'confirm_resp' res.id%}';">Согласиться</button>

        {% endif %}
        <button onclick="window.location.href = '{% url 'delete_resp' res.id%}';">Отказаться</button>


    </div>
    {% endfor %}
    {% endif %}
  </div>

{% endfor %}

{% endif %}



{% endblock content %}

BulletinBoard/templates/default.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}

            {%endblock title%}
        </title>
        <!-- Favicon-->

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">

                <a class="navbar-brand" href="#">{% block front %} {%endblock front%}</a>
                {% if user.id %}
                <a class="navbar-brand" href="{% url 'account_logout' %}">Log out</a>
                {% endif %}
                {% if user.id %}
                <a class="navbar-brand" href='{% url 'user' user.id %}'>{{ user.username}}</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'account_login' %}">Log in</a>
                {% endif %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Объявления</a></li>
                        <li class="nav-item"><a class="nav-link" href='{% url 'create' %}'>Создать объявление</a></li>
                        <li class="nav-item"><a class="nav-link" href='{% url 'search' %}'>Search</a></li>




                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
   <div class="row">
       <div class="col-lg-12 text-center">
           {% block content %}

           {% endblock content %}
       </div>
       <div class="col-lg-12 text-left">
           {% block text %}

           {% endblock text %}
       </div>
   </div>
</div>

    </body>
</html>